#pragma once

enum
{
	BYPASS_OFF,
	BYPASS_ON,
	BYPASS_LEN
};

enum
{
	MODE_AUTO,
	MODE_MANUAL,
	MODE_LEN
};

enum class DeviceStatus
{
	STATUS_INITIALIZE_START,
	STATUS_INITIALIZE_END,
	STATUS_IN_PUNCH_POS,
	STATUS_IN_PLATE_INSERT,
	STATUS_IN_PLATE_EXIST1,
	STATUS_IN_PLATE_EXIST2,
	STATUS_OUT_ROLLER_CW,
	STATUS_OUT_ROLLER_CCW,
	STATUS_OUT_LSTP_B_DOWN,
	STATUS_OUT_LSTP_B_UP,
	STATUS_OUT_CENTER_OFF,
	STATUS_OUT_CENTER_ON,
	STATUS_OUT_PSTP_B_DOWN,
	STATUS_OUT_PSTP_B_UP,
	STATUS_OUT_LSTP_A_DOWN,
	STATUS_OUT_LSTP_A_UP,
	STATUS_OUT_PSTP_A_DOWN,
	STATUS_OUT_PSTP_A_UP,
	STATUS_OUT_PL_CLAMP,
	STATUS_OUT_PL_ROTATE,
	STATUS_OUT_PUNCH_ON,
	STATUS_OUT_PUNCH_OFF,
	STATUS_OUT_ROLLER_UP,
	STATUS_OUT_CAMERA_DOWN,
	STATUS_OUT_ROLLER_DOWN,
	STATUS_OUT_CAMERA_UP,
	STATUS_OUT_VACUUM_OFF,
	STATUS_OUT_VACUUM_ON,
	STATUS_CAMERA1_SEARCHMARK_ERROR,
	STATUS_CAMERA2_SEARCHMARK_ERROR,
	STATUS_LEN
};

// DO OFF 명령 내릴 때 사용 (복동이라 Timer 사용하여 지령 내림)
enum
{
	OFFTIMERID_ROLLER_CW,
	OFFTIMERID_ROLLER_CCW,
	OFFTIMERID_LSTP_B_DOWN,
	OFFTIMERID_LSTP_B_UP,
	OFFTIMERID_CENTER_OFF,
	OFFTIMERID_CENTER_ON,
	OFFTIMERID_PSTP_A_DOWN,
	OFFTIMERID_PSTP_A_UP,
	OFFTIMERID_LSTP_A_DOWN,
	OFFTIMERID_LSTP_A_UP,
	OFFTIMERID_PSTP_B_DOWN,
	OFFTIMERID_PSTP_B_UP,
	OFFTIMERID_PL_CLAMP,
	OFFTIMERID_PL_ROTATE,
	OFFTIMERID_PUNCH_ON,
	OFFTIMERID_PUNCH_OFF,
	OFFTIMERID_ROLLER_UP,
	OFFTIMERID_ROLLER_DOWN,
	OFFTIMERID_CAMERA_UP,
	OFFTIMERID_CAMERA_DOWN,
	OFFTIMERID_VACUUM_OFF,
	OFFTIMERID_VACUUM_ON,
	OFFTIMERID_LEN
};

enum
{
	TIMERID_INITIALIZE = 100,
	TIMERID_AUTOSEQUENCE,
	TIMERID_PLATEIN,
	TIMERID_CENTERING,
	TIMERID_CLAMP,
	TIMERID_ALIGNMENT,
	TIMERID_PUNCH,
	TIMERID_EJECT,
	TIMERID_ROTATE,
	TIMERID_EXIT
};