#pragma once
/*
	IO 접점에 대해 정리한 헤더파일 입니다.
*/

// IN 
enum
{
	IO_IN_PUNCH_ON,
	IO_IN_PUNCH_OFF,
	IO_IN_PL_CLAMP_UP,
	IO_IN_PL_CLAMP_DOWN,
	IO_IN_CAMERA_UP,
	IO_IN_CAMERA_DOWN,
	IO_IN_PSTP_A_UP,
	IO_IN_PSTP_A_DOWN,
	IO_IN_PSTP_B_UP,
	IO_IN_PSTP_B_DOWN,
	IO_IN_TEMP0,
	IO_IN_ROLLER_UP,
	IO_IN_ROLLER_DOWN,
	IO_IN_PL_ROTATE_ON,
	IO_IN_PL_ROTATE_OFF,
	IO_IN_VACUUM_ON,
	IO_IN_LSTP_A_DOWN,
	IO_IN_LSTP_A_UP,
	IO_IN_LSTP_B_UP,
	IO_IN_LSTP_B_DOWN,
	IO_IN_CENTER_OFF,
	IO_IN_CENTER_ON,
	IO_IN_PUNCH_IN,
	IO_IN_TEMP1,
	IO_IN_PLATE_IN,
	IO_IN_PLATE_A_ON,
	IO_IN_PLATE_B_ON,
	IO_IN_LEN
};

// OUT
enum
{
	IO_OUT_ROLLER_CW,
	IO_OUT_ROLLER_CCW,
	IO_OUT_LSTP_B_DOWN,
	IO_OUT_LSTP_B_UP,
	IO_OUT_CENTER_OFF,
	IO_OUT_CENTER_ON,
	IO_OUT_PSTP_A_DOWN,
	IO_OUT_PSTP_A_UP,
	IO_OUT_LSTP_A_DOWN,
	IO_OUT_LSTP_A_UP,
	IO_OUT_PSTP_B_DOWN,
	IO_OUT_PSTP_B_UP,
	IO_OUT_PL_CLAMP,
	IO_OUT_PL_ROTATE,
	IO_OUT_PUNCH_ON,
	IO_OUT_PUNCH_OFF,
	IO_OUT_ROLLER_UP,
	IO_OUT_ROLLER_DOWN,
	IO_OUT_CAMERA_UP,
	IO_OUT_CAMERA_DOWN,
	IO_OUT_VACUUM_OFF,
	IO_OUT_VACUUM_ON,
	IO_OUT_LEN
};
